### ISSUE TITLE
刷课进度不显示百分百

### ISSUE THREAD

**Issue by awelling2** [VishvaWang/jstool#1]
1. 把脚本复制到firefox控制台提示，Chrome没提示
`已拦截跨源请求：同源策略禁止读取位于 http://zjy2.icve.com.cn/student/learning/getLearnningCourseList 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。`（不知道有没有关系）

2. 然后就是刷课过程中在首页有部分课程不会显示百分之百
web端右侧的进度没有显示100%，在安卓端发现有些课程有“子节点”分级还有一些视频一些没有刷到
由于本人没有学过js，麻烦作者帮忙看一下，谢谢谢谢谢谢

**Comment by awelling2** [comment]
过了一天，有些账号是显示百分百了，但是子节点的确不可以刷到

**Comment by ghost** [comment]
1.这个不太清楚,我用的是chrome,应该没有影响.
2.进度不显示100%   手动刷课不会出现这个问题.似乎是这个职教云系统存在的隐藏bug被我的刷课方式给暴露出来了.解决方法只能是要么等它得后台修复到这个bug,要么我完全用脚本模拟手动刷课(我觉得对服务器来讲我的刷课脚本和手动似乎是一样的,除了手动刷课不可能短时间发送这么大量得请求),但是由于目前脚本勉强能用(第二天会恢复百分百).并且实际上讲我很难定位bug,(到底什么原因导致服务器计算出错误的进度呢?)所以我决定不修复这个bug.
2.有部分子节点视频没有刷到  我用我同学得账号都没有遇到这个问题,请问你说的每刷到是进度没有刷完还是完全刷不到,如果是完全刷不到我怀疑是我们的课程结构和你们的不一样,而我是按照我们的课程结构编写的脚本.可以的话提供个账号或者你自己用浏览器抓包看一下.我会估计一下工作量,如果简单的话我可以顺手帮忙改改.

**Comment by awelling2** [comment]
- 子节点只能在安卓端看到
安卓端：<img width="300" height="400" src="https://user-images.githubusercontent.com/17465191/50813516-9b485b80-1351-11e9-99e1-798b593807de.png"/>
电脑端：<img width="300" height="400" src="https://user-images.githubusercontent.com/17465191/50813514-97b4d480-1351-11e9-8296-27126ab2dde1.png"/>
IOS端：<img width="300" height="400" src="https://user-images.githubusercontent.com/17465191/50813757-5ffa5c80-1352-11e9-8a03-215c7c1eb603.png"/>

- 安卓手机用Packet Capture抓的包（以下抓包的子节点位于”运动系统“下的”骨骼肌“下的）

1. ` {"code":1,"msg":"获取成功！","moduleList":{"moduleId":"ga8kaxwpjpxkgcxyxizwa","isFirstModule":0,"moduleName":"绪论","sortOrder":14},{"moduleId":"ga8kaxwpobg3ydwfyrfig","isFirstModule":0,"moduleName":"运动系统","sortOrder":15},{"moduleId":"gq8kaxwp66lls6lkjxb8yg","isFirstModule":0,"moduleName":"内脏学总论","sortOrder":16},{"moduleId":"gw8kaxwpi9ie4luvbhjeq","isFirstModule":0,"moduleName":"内分泌系统","sortOrder":27}]}`

2. ` {"code":1,"msg":"获取成功！","topicList":[{"topicId":"ga8kaxwpg4voatqbcwp1ia","topicName":"骨学","sortOrder":0,"upTopicId":"0"},{"topicId":"ga8kaxwp1ormo5mzgbu3tg","topicName":"骨连结","sortOrder":1,"upTopicId":"ga8kaxwpg4voatqbcwp1ia"},{"topicId":"gq8kaxwpojjgcrti5yt4pw","topicName":"骨骼肌","sortOrder":2,"upTopicId":"ga8kaxwp1ormo5mzgbu3tg"}]}`

3. `{"code":1,"msg":"获取成功！","cellList":[{"topicId":"gq8kaxwpojjgcrti5yt4pw","cellId":"gq8kaxwp2ynn9ij1snmna","upCellId":"-1","cellType":4,"sortOrder":0,"cellName":"骨骼肌","cellContent":"","categoryName":"子节点","externalLinkUrl":"","extension":"其他","isAllowDownLoad":false,"cellChildNodeList":[{"cellId":"gq8kaxwpfjrarrapmlo1aa","upCellId":"0","cellType":1,"sortOrder":0,"cellName":"3 骨骼肌的重点和难点.pdf","cellContent":"","categoryName":"文档","externalLinkUrl":"","extension":"office","isAllowDownLoad":false,"isStuSeeCell":1},{"cellId":"gq8kaxwpgadogyxs8dn8a","upCellId":"gq8kaxwpfjrarrapmlo1aa","cellType":1,"sortOrder":1,"cellName":"4骨骼肌教学要求.pdf","cellContent":"","categoryName":"文档","externalLinkUrl":"","extension":"office","isAllowDownLoad":false,"isStuSeeCell":1}],"isStuSeeCell":1},{"topicId":"gq8kaxwpojjgcrti5yt4pw","cellId":"gq8kaxwpaipefykdki5nha","upCellId":"-1","cellType":4,"sortOrder":1,"cellName":"骨骼肌概述","cellContent":"","categoryName":"子节点","externalLinkUrl":"","extension":"其他","isAllowDownLoad":false,"cellChildNodeList":[{"cellId":"gq8kaxwpvprgynaabefuka","upCellId":"gq8kaxwpgadogyxs8dn8a","cellType":1,"sortOrder":0,"cellName":"骨骼肌概述.pptx","cellContent":"","categoryName":"ppt","externalLinkUrl":"","extension":"office","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpa5rlrxvksduztg","upCellId":"gq8kaxwpvprgynaabefuka","cellType":1,"sortOrder":1,"cellName":"肌肉总论.mp4","cellContent":"","categoryName":"视频","externalLinkUrl":"","extension":"video","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpk7fkza79jpqa4q","upCellId":"gq8kaxwpa5rlrxvksduztg","cellType":1,"sortOrder":2,"cellName":"全身肌肉1.bmp","cellContent":"","categoryName":"图片","externalLinkUrl":"","extension":"img","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwp5bjb2aujv5dtw","upCellId":"gq8kaxwpk7fkza79jpqa4q","cellType":1,"sortOrder":3,"cellName":"全身肌肉2.bmp","cellContent":"","categoryName":"图片","externalLinkUrl":"","extension":"img","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwp7bzba80lbcvava","upCellId":"gq8kaxwp5bjb2aujv5dtw","cellType":1,"sortOrder":4,"cellName":"肌的各种形状.bmp","cellContent":"","categoryName":"图片","externalLinkUrl":"","extension":"img","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpui1ijgkxq0s42a","upCellId":"gq8kaxwp7bzba80lbcvava","cellType":1,"sortOrder":5,"cellName":"肌的横断面等.bmp","cellContent":"","categoryName":"图片","externalLinkUrl":"","extension":"img","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpdpxbnfhg7tm3kq","upCellId":"gq8kaxwpui1ijgkxq0s42a","cellType":1,"sortOrder":6,"cellName":"肌肉分类.bmp","cellContent":"","categoryName":"图片","externalLinkUrl":"","extension":"img","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpi5loa0l7z3zpg","upCellId":"gq8kaxwpdpxbnfhg7tm3kq","cellType":1,"sortOrder":7,"cellName":"骨骼肌结构.mov","cellContent":"","categoryName":"视频","externalLinkUrl":"","extension":"video","isAllowDownLoad":false,"isStuSeeCell":0}],"isStuSeeCell":1},{"topicId":"gq8kaxwpojjgcrti5yt4pw","cellId":"gq8kaxwpqb1kdhxqr55w","upCellId":"-1","cellType":4,"sortOrder":2,"cellName":"头颈躯干肌","cellContent":"","categoryName":"子节点","externalLinkUrl":"","extension":"其他","isAllowDownLoad":false,"cellChildNodeList":[{"cellId":"gq8kaxwphprnunikxztnva","upCellId":"gq8kaxwpi5loa0l7z3zpg","cellType":1,"sortOrder":0,"cellName":"头颈躯干骨骼肌.pptx","cellContent":"","categoryName":"ppt","externalLinkUrl":"","extension":"office","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwps6rnkkodswbeba","upCellId":"gq8kaxwphprnunikxztnva","cellType":1,"sortOrder":1,"cellName":"头肌.mp4","cellContent":"","categoryName":"视频","externalLinkUrl":"","extension":"video","isAllowDownLoad":false,"isStuSeeCell":0},{"cellId":"gq8kaxwpej1nqyusmsw5q","upCellId":"gq8kaxwps6rnkkodswbeba"`

**Comment by ghost** [comment]
已全部修复,感谢提交的反馈以及测试用账号
